# Generated by Django 3.1 on 2020-09-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_title', models.CharField(max_length=200)),
                ('segment_content', models.TextField(default='Some string')),
            ],
        ),
    ]
