# Generated by Django 3.1 on 2020-09-07 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200903_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_git_url',
            field=models.TextField(default='String'),
        ),
    ]
