# Generated by Django 3.1 on 2020-09-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_project_git_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='intro_education',
            field=models.TextField(default='Some string'),
        ),
    ]
