# Generated by Django 3.1 on 2020-09-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200912_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='second_intro_content',
            field=models.TextField(default='Some string'),
        ),
    ]
