# Generated by Django 3.1 on 2020-09-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_introduction_second_intro_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.TextField(default='Some string')),
                ('tool_rating', models.TextField(default='Some string')),
            ],
        ),
        migrations.DeleteModel(
            name='Abilities',
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
        migrations.AddField(
            model_name='language',
            name='language_name',
            field=models.TextField(default='Some string'),
        ),
        migrations.AddField(
            model_name='language',
            name='language_rating',
            field=models.TextField(default='Some string'),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_name',
            field=models.TextField(default='Some string'),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_rating',
            field=models.TextField(default='Some string'),
        ),
    ]
