# Generated by Django 3.1 on 2020-09-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_connect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connect',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='twitter_url',
        ),
        migrations.AddField(
            model_name='connect',
            name='my_url',
            field=models.TextField(default='Some string'),
        ),
        migrations.AddField(
            model_name='connect',
            name='social_network',
            field=models.TextField(default='Some string'),
        ),
    ]
